# Generated by Django 4.2 on 2024-05-08 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preventas', '0002_preventa_usuario_teknica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preventa',
            old_name='usuario_teknica',
            new_name='usuario_teknica_id',
        ),
    ]
