# Generated by Django 4.2 on 2024-05-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preventas', '0003_rename_usuario_teknica_preventa_usuario_teknica_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preventa',
            old_name='usuario_teknica_id',
            new_name='usuario_teknica',
        ),
    ]
