# Generated by Django 4.2 on 2024-05-08 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preventas', '0004_rename_usuario_teknica_id_preventa_usuario_teknica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventa',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventas.cliente'),
        ),
        migrations.AlterField(
            model_name='preventa',
            name='usuario_teknica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
